### PR TITLE
Fixed version issue

### PR DESCRIPTION
**Pull request by adambratt**
Found the solution to all of the problems!

### CODE REVIEW

**Comment by adambratt** [comment]
@nicholaswyoung ?

**Comment by nicholaswyoung** [comment]
http://blog.npmjs.org/post/77758351673/no-more-npm-publish-f

**Comment by rgarrison3** [comment]
@nicholaswyoung thanks for the clarification I have contacted the NPM authors as well, can we get this reopened and merged? They are going to work on something on there end as well!

**Comment by nicholaswyoung** [comment]
@rgarrison3 I don't expect npm to change policy for this one issue. So at this point, the best course of action is to use 1.0.1. 

If I hear from the npm team, I'll merge and reissue. But for now, I haven't heard anything and they would need to contact me before merging versions.

**Pull request closed without merging**
